version: 2
updates:
  - package-ecosystem: composer
    directory: /app
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      composer:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      composer-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /app/frontend
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      npm:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      npm-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      github-actions:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      github-actions-security:
        applies-to: security-updates
        patterns:
          - "*"
