version: "3.7"

services:
    php:
        build:
            context: ./php
        restart: unless-stopped
        env_file:
            - ../.env
            - path: ../.env.local
              required: false
        volumes:
            - ../app:/application/app
            - ../data:/application/data
            - ../var:/application/var
        networks:
            - phritzbox

networks:
    phritzbox:
        name: "${COMPOSE_PROJECT_NAME}"
        external: false

# vim: syntax=yaml ts=2 sw=2 et sr softtabstop=2 autoindent