FROM dunglas/frankenphp:1-php8.5-bookworm

RUN apt-get update && apt-get install -y \
        libsqlite3-dev \
    && install-php-extensions pdo_sqlite \
    && rm -rf /var/lib/apt/lists/*

COPY Caddyfile /etc/caddy/Caddyfile

WORKDIR /application
