# Map devices to classes
#
# Manufacturer and Device Name have to be all lowercase.
#
# Structure of this file is
# 'manufacturer'
#   'device name': '\\Device\\Class\\Name'

'avm':
    'fritz!dect 200':           '\App\Device\Avm\FritzDect200'
    'fritz!powerline 546e':     '\App\Device\Avm\FritzPowerline546E'
